// ══════════════════════════════════════════════
// CARSENSE — Data Module
// ══════════════════════════════════════════════

// ── System Images ───────────────────────────
export const systemImages = {
  frenos: "https://images.unsplash.com/photo-1761040100208-07f603acc83f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  motor: "https://images.unsplash.com/photo-1768929571671-4e58e2d9e72f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  suspension: "https://images.unsplash.com/photo-1760836395865-0c20fff2aefd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  electrico: "https://images.unsplash.com/photo-1737309469386-68fb1499a8c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  enfriamiento: "https://images.unsplash.com/photo-1760804462141-442810513d4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  escape: "https://images.unsplash.com/photo-1760448970487-a3c6ff323b0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
};

export const componentImages = {
  "pastillas-freno": "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "disco-freno": "https://images.unsplash.com/photo-1761040100208-07f603acc83f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "pinzas-freno": "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "liquido-frenos": "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "cilindro-maestro": "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  servofreno: "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "filtro-aire": "https://images.unsplash.com/photo-1768929571671-4e58e2d9e72f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  bujias: "https://images.unsplash.com/photo-1590488630628-df246379beab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "correa-distribucion": "https://images.unsplash.com/photo-1573864698664-4a1fd0c97b46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "bomba-combustible": "https://images.unsplash.com/photo-1764538737417-3345e9f649e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "sensor-oxigeno": "https://images.unsplash.com/photo-1768929571671-4e58e2d9e72f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "filtro-combustible": "https://images.unsplash.com/photo-1764538737417-3345e9f649e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  amortiguadores: "https://images.unsplash.com/photo-1769218403508-90c67335aab5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  resortes: "https://images.unsplash.com/photo-1760836395865-0c20fff2aefd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  rotulas: "https://images.unsplash.com/photo-1760836395865-0c20fff2aefd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "barra-estabilizadora": "https://images.unsplash.com/photo-1769218403508-90c67335aab5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  bateria: "https://images.unsplash.com/photo-1737309469386-68fb1499a8c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  alternador: "https://images.unsplash.com/photo-1674655798804-b739c31b6cf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "motor-arranque": "https://images.unsplash.com/photo-1674655798804-b739c31b6cf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  fusibles: "https://images.unsplash.com/photo-1737309469386-68fb1499a8c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  radiador: "https://images.unsplash.com/photo-1760804462141-442810513d4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  termostato: "https://images.unsplash.com/photo-1730461747568-7250e49eb50c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "bomba-agua": "https://images.unsplash.com/photo-1760804462141-442810513d4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  refrigerante: "https://images.unsplash.com/photo-1730461747568-7250e49eb50c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  catalizador: "https://images.unsplash.com/photo-1759419281419-b04552b2691a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  silenciador: "https://images.unsplash.com/photo-1760448970487-a3c6ff323b0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "sensor-lambda": "https://images.unsplash.com/photo-1759419281419-b04552b2691a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
  "tuberia-escape": "https://images.unsplash.com/photo-1760448970487-a3c6ff323b0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&q=80",
};

// ── Systems ─────────────────────────────────
export const systems = [
  { id: "motor", name: "Motor y Combustible", desc: "Corazón del vehículo. Convierte combustible en energía mecánica para mover el auto.", color: "#e03030", components: 6, symptoms: 12 },
  { id: "suspension", name: "Suspensión", desc: "Amortigua muelles y mantiene el contacto de las ruedas con el pavimento.", color: "#f59e0b", components: 4, symptoms: 9 },
  { id: "electrico", name: "Sistema Eléctrico", desc: "Alimenta todos los sistemas electrónicos: luces, arranque y sensores del vehículo.", color: "#3b82f6", components: 4, symptoms: 14 },
  { id: "enfriamiento", name: "Enfriamiento", desc: "Regula la temperatura del motor para evitar el sobrecalentamiento.", color: "#06b6d4", components: 4, symptoms: 8 },
  { id: "frenos", name: "Sistema de Frenos", desc: "Desacelera y detiene el vehículo mediante fricción entre pastillas y discos.", color: "#10b981", components: 6, symptoms: 11 },
  { id: "escape", name: "Sistema de Escape", desc: "Expulsa los gases de combustión y reduce el ruido y las emisiones contaminantes.", color: "#f97316", components: 4, symptoms: 6 },
];

// ── Systems Detail Data ──────────────────────
export const systemsData = {
  frenos: {
    name: "Sistema de Frenos", color: "#10b981",
    desc: "Responsable de desacelerar y detener el vehículo de forma segura. Funciona mediante la fricción entre pastillas y discos (o tambores). Es uno de los sistemas más críticos para la seguridad del conductor.",
    criticality: "Alta",
    hotpoints: [
      { id: "pastillas-freno", name: "Pastillas de Freno", x: 22, y: 60 },
      { id: "disco-freno", name: "Disco de Freno", x: 40, y: 45 },
      { id: "pinzas-freno", name: "Pinzas de Freno", x: 32, y: 28 },
      { id: "liquido-frenos", name: "Líquido de Frenos", x: 72, y: 30 },
      { id: "cilindro-maestro", name: "Cilindro Maestro", x: 82, y: 55 },
      { id: "servofreno", name: "Servofreno", x: 88, y: 70 },
    ],
    components: [
      { id: "pastillas-freno", name: "Pastillas de Freno", desc: "Material de fricción que presiona el disco para frenar." },
      { id: "disco-freno", name: "Disco de Freno", desc: "Pieza metálica circular que rota con la rueda." },
      { id: "pinzas-freno", name: "Pinzas de Freno", desc: "Regula pastillas y las presiona contra el disco." },
      { id: "liquido-frenos", name: "Líquido de Frenos", desc: "Fluido hidráulico que transmite la presión del pedal." },
      { id: "cilindro-maestro", name: "Cilindro Maestro", desc: "Convierte la fuerza del pedal en presión hidráulica." },
      { id: "servofreno", name: "Servofreno (Booster)", desc: "Amplifica la fuerza aplicada sobre el pedal." },
    ],
    symptoms: [
      { label: "Ruido al frenar", resultId: "1" },
      { label: "Vibración al frenar", resultId: "2" },
      { label: "Pedal esponjoso", resultId: "1" },
      { label: "Auto vira a un lado al frenar", resultId: "1" },
      { label: "Pedal va al piso", resultId: "1" },
      { label: "Luz de frenos encendida", resultId: "1" },
    ],
    maintenance: [
      { label: "Pastillas de Freno", interval: "Revisar cada 20,000 km o 1 año. Reemplazar cuando el grosor baje de 3mm." },
      { label: "Líquido de Frenos", interval: "Cambiar cada 2 años o 40,000 km independientemente de su apariencia." },
      { label: "Discos de Freno", interval: "Inspeccionar en cada cambio de pastillas. Reemplazar si hay ranuras profundas." },
    ],
  },
  motor: {
    name: "Motor y Combustible", color: "#e03030",
    desc: "Corazón del vehículo. Convierte el combustible en energía mecánica a través de ciclos de combustión controlada.",
    criticality: "Alta",
    hotpoints: [
      { id: "filtro-aire", name: "Filtro de Aire", x: 18, y: 25 },
      { id: "bujias", name: "Bujías", x: 45, y: 35 },
      { id: "correa-distribucion", name: "Correa Distribución", x: 30, y: 60 },
      { id: "bomba-combustible", name: "Bomba Combustible", x: 70, y: 75 },
      { id: "sensor-oxigeno", name: "Sensor O2", x: 80, y: 45 },
      { id: "filtro-combustible", name: "Filtro Combustible", x: 55, y: 70 },
    ],
    components: [
      { id: "filtro-aire", name: "Filtro de Aire", desc: "Filtra partículas antes de la admisión al motor." },
      { id: "bujias", name: "Bujías", desc: "Generan la chispa que enciende la mezcla aire/combustible." },
      { id: "correa-distribucion", name: "Correa de Distribución", desc: "Sincroniza el movimiento del cigüeñal y los árboles de levas." },
      { id: "bomba-combustible", name: "Bomba de Combustible", desc: "Suministra combustible al motor desde el tanque." },
      { id: "sensor-oxigeno", name: "Sensor de Oxígeno", desc: "Mide el oxígeno en los gases de escape para optimizar la mezcla." },
      { id: "filtro-combustible", name: "Filtro de Combustible", desc: "Retiene impurezas del combustible antes del motor." },
    ],
    symptoms: [
      { label: "Pérdida de potencia", resultId: "4" },
      { label: "Luz de check engine", resultId: "5" },
      { label: "Ruido de motor", resultId: "4" },
      { label: "Humo negro del escape", resultId: "4" },
      { label: "Consumo excesivo de combustible", resultId: "4" },
      { label: "Dificultad al arrancar", resultId: "4" },
    ],
    maintenance: [
      { label: "Cambio de aceite", interval: "Cada 5,000–10,000 km según tipo de aceite." },
      { label: "Bujías", interval: "Cada 30,000–60,000 km según tipo." },
      { label: "Filtro de aire", interval: "Cada 15,000–30,000 km o anualmente." },
    ],
  },
  suspension: {
    name: "Suspensión", color: "#f59e0b",
    desc: "Amortigua los golpes del camino y mantiene el contacto de las ruedas con el pavimento, asegurando confort y estabilidad.",
    criticality: "Media",
    hotpoints: [
      { id: "amortiguadores", name: "Amortiguadores", x: 25, y: 40 },
      { id: "resortes", name: "Resortes", x: 65, y: 35 },
      { id: "rotulas", name: "Rótulas", x: 30, y: 65 },
      { id: "barra-estabilizadora", name: "Barra Estabilizadora", x: 50, y: 75 },
    ],
    components: [
      { id: "amortiguadores", name: "Amortiguadores", desc: "Absorben la energía de los baches y vibraciones." },
      { id: "resortes", name: "Resortes", desc: "Soportan el peso del vehículo y absorben impactos." },
      { id: "rotulas", name: "Rótulas", desc: "Permiten la articulación entre la suspensión y las ruedas." },
      { id: "barra-estabilizadora", name: "Barra Estabilizadora", desc: "Reduce el balanceo lateral del vehículo en curvas." },
    ],
    symptoms: [
      { label: "Vibración en el volante", resultId: "2" },
      { label: "Auto baila en curvas", resultId: "2" },
      { label: "Ruido de golpe en baches", resultId: "2" },
      { label: "Desgaste irregular de llantas", resultId: "2" },
      { label: "Auto jala a un lado", resultId: "2" },
    ],
    maintenance: [
      { label: "Amortiguadores", interval: "Revisar cada 50,000–80,000 km o si hay rebote excesivo." },
      { label: "Rótulas", interval: "Inspeccionar cada 60,000 km o ante ruidos y juego en ruedas." },
    ],
  },
  electrico: {
    name: "Sistema Eléctrico", color: "#3b82f6",
    desc: "Alimenta todos los sistemas electrónicos del vehículo: luces, arranque, sensores, control de motor y comodidades.",
    criticality: "Media",
    hotpoints: [
      { id: "bateria", name: "Batería", x: 20, y: 35 },
      { id: "alternador", name: "Alternador", x: 45, y: 45 },
      { id: "motor-arranque", name: "Motor de Arranque", x: 65, y: 55 },
      { id: "fusibles", name: "Fusibles y Relés", x: 78, y: 30 },
    ],
    components: [
      { id: "bateria", name: "Batería", desc: "Almacena energía eléctrica para el arranque y sistemas auxiliares." },
      { id: "alternador", name: "Alternador", desc: "Genera electricidad mientras el motor está en marcha." },
      { id: "motor-arranque", name: "Motor de Arranque", desc: "Motor eléctrico que gira el motor para encenderlo." },
      { id: "fusibles", name: "Fusibles y Relés", desc: "Protegen los circuitos eléctricos de sobrecargas." },
    ],
    symptoms: [
      { label: "Batería descargada", resultId: "6" },
      { label: "Luces tenues", resultId: "5" },
      { label: "Carro no arranca", resultId: "6" },
      { label: "Luz de batería encendida", resultId: "5" },
      { label: "Alternador con ruido", resultId: "6" },
    ],
    maintenance: [
      { label: "Batería", interval: "Revisar cada 2 años. Reemplazar cada 3–5 años." },
      { label: "Alternador", interval: "Revisar ante indicios de descarga o luces fluctuantes." },
    ],
  },
  enfriamiento: {
    name: "Sistema de Enfriamiento", color: "#06b6d4",
    desc: "Regula la temperatura del motor para evitar el sobrecalentamiento. Circula refrigerante para disipar el calor generado en la combustión.",
    criticality: "Alta",
    hotpoints: [
      { id: "radiador", name: "Radiador", x: 15, y: 40 },
      { id: "termostato", name: "Termostato", x: 45, y: 35 },
      { id: "bomba-agua", name: "Bomba de Agua", x: 55, y: 55 },
      { id: "refrigerante", name: "Refrigerante", x: 75, y: 40 },
    ],
    components: [
      { id: "radiador", name: "Radiador", desc: "Disipa el calor del refrigerante hacia el exterior." },
      { id: "termostato", name: "Termostato", desc: "Regula el flujo de refrigerante según la temperatura." },
      { id: "bomba-agua", name: "Bomba de Agua", desc: "Impulsa el refrigerante a través del sistema." },
      { id: "refrigerante", name: "Refrigerante", desc: "Líquido que absorbe y disipa el calor del motor." },
    ],
    symptoms: [
      { label: "Motor recalentado", resultId: "3" },
      { label: "Temperatura sube erráticamente", resultId: "8" },
      { label: "Vapor bajo el cofre", resultId: "3" },
      { label: "Pérdida de refrigerante", resultId: "3" },
    ],
    maintenance: [
      { label: "Refrigerante", interval: "Cambiar cada 2 años o 40,000 km." },
      { label: "Termostato", interval: "Inspeccionar cada 60,000 km o ante variaciones de temperatura." },
    ],
  },
  escape: {
    name: "Sistema de Escape", color: "#f97316",
    desc: "Expulsa los gases de combustión y reduce el ruido y las emisiones contaminantes del vehículo.",
    criticality: "Media",
    hotpoints: [
      { id: "catalizador", name: "Catalizador", x: 30, y: 45 },
      { id: "silenciador", name: "Silenciador", x: 60, y: 55 },
      { id: "sensor-lambda", name: "Sensor Lambda", x: 20, y: 35 },
      { id: "tuberia-escape", name: "Tubería", x: 80, y: 65 },
    ],
    components: [
      { id: "catalizador", name: "Catalizador", desc: "Reduce emisiones contaminantes de los gases de escape." },
      { id: "silenciador", name: "Silenciador", desc: "Reduce el ruido producido por los gases de escape." },
      { id: "sensor-lambda", name: "Sensor Lambda", desc: "Mide el contenido de oxígeno en los gases de escape." },
      { id: "tuberia-escape", name: "Tubería de Escape", desc: "Conduce los gases desde el motor hasta el exterior." },
    ],
    symptoms: [
      { label: "Olor a quemado", resultId: "6" },
      { label: "Humo excesivo", resultId: "7" },
      { label: "Ruido fuerte de escape", resultId: "6" },
      { label: "Pérdida de potencia", resultId: "7" },
    ],
    maintenance: [
      { label: "Catalizador", interval: "Inspeccionar cada 80,000 km o ante pérdida de potencia." },
      { label: "Sistema de escape", interval: "Revisar fugas cada 2 años o 40,000 km." },
    ],
  },
};

// ── Components Data ──────────────────────────
export const componentsData = {
  "pastillas-freno": {
    name: "Pastillas de Freno",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Material de fricción que presiona el disco para generar la fuerza de frenado.",
    wear: 82, wearStatus: "critical",
    wearLabel: "82% de desgaste — Reemplazo urgente recomendado",
    specs: [
      { label: "Material", value: "Semimetálico / Orgánico / Cerámico" },
      { label: "Grosor mínimo", value: "3 mm" },
      { label: "Grosor nuevo", value: "10–12 mm" },
      { label: "Vida útil", value: "15,000–70,000 km" },
    ],
    symptoms: ["Chirrido metálico al frenar", "Vibración en el pedal", "Pedal con más recorrido", "Olor a quemado tras frenar"],
    tips: ["Revisar el nivel del líquido de frenos regularmente.", "No esperes al indicador de desgaste para revisar las pastillas.", "Reemplazar en pares (eje delantero o trasero completo)."],
  },
  "disco-freno": {
    name: "Disco de Freno",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Pieza metálica circular que rota con la rueda y recibe la fricción de las pastillas.",
    wear: 55, wearStatus: "warning",
    wearLabel: "55% — Revisar próximamente en siguiente mantenimiento",
    specs: [
      { label: "Material", value: "Hierro fundido / Carbono-cerámica" },
      { label: "Grosor mínimo", value: "Varía por modelo" },
      { label: "Vida útil", value: "60,000–100,000 km" },
    ],
    symptoms: ["Vibración al frenar", "Ranuras visibles en el disco", "Ruido de raspado", "Disco con variación de grosor"],
    tips: ["Inspeccionar en cada cambio de pastillas.", "Nunca enfriar con agua cuando está caliente.", "Reemplazar si tiene ranuras profundas o deformación."],
  },
  "pinzas-freno": {
    name: "Pinzas de Freno",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Componente hidráulico que presiona las pastillas contra el disco al frenar.",
    wear: 25, wearStatus: "ok",
    wearLabel: "25% — En buen estado",
    specs: [
      { label: "Tipo", value: "Flotante / Fija" },
      { label: "Pistones", value: "1–6 según modelo" },
      { label: "Vida útil", value: "100,000–150,000 km" },
    ],
    symptoms: ["Fuga de líquido de frenos", "Freno jalando a un lado", "Pinza atascada (freno caliente)", "Pedal esponjoso"],
    tips: ["Revisar fugas en cada mantenimiento.", "No forzar el pistón sin purgar el sistema.", "Lubricar los guías regularmente."],
  },
  "liquido-frenos": {
    name: "Líquido de Frenos",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Fluido hidráulico que transmite la presión del pedal hacia las pinzas.",
    wear: 60, wearStatus: "warning",
    wearLabel: "60% — Cambio próximo recomendado",
    specs: [
      { label: "Especificación", value: "DOT 3, DOT 4 o DOT 5.1" },
      { label: "Punto de ebullición", value: "205–270°C (seco)" },
      { label: "Cambio recomendado", value: "Cada 2 años o 40,000 km" },
    ],
    symptoms: ["Pedal esponjoso o blando", "Frenos menos efectivos", "Nivel bajo en depósito", "Líquido oscuro o turbio"],
    tips: ["Verificar el nivel mensualmente.", "No mezclar tipos de líquido DOT.", "Cambiar cada 2 años aunque no esté oscuro."],
  },
  "cilindro-maestro": {
    name: "Cilindro Maestro",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Convierte la fuerza mecánica del pedal en presión hidráulica.",
    wear: 20, wearStatus: "ok",
    wearLabel: "20% — En buen estado",
    specs: [
      { label: "Tipo", value: "Doble circuito (tándem)" },
      { label: "Vida útil", value: "150,000–200,000 km" },
    ],
    symptoms: ["Pedal cae al fondo", "Pérdida gradual de presión", "Fuga interna", "Líquido bajo sin fugas visibles"],
    tips: ["Inspeccionar ante pedal blando persistente.", "No reparar internamente — reemplazar completo.", "Verificar el depósito de líquido regularmente."],
  },
  servofreno: {
    name: "Servofreno (Booster)",
    system: "Sistema de Frenos", systemId: "frenos", systemColor: "#10b981",
    desc: "Amplifica la fuerza aplicada sobre el pedal usando vacío del motor.",
    wear: 15, wearStatus: "ok",
    wearLabel: "15% — En buen estado",
    specs: [
      { label: "Tipo", value: "Vacío / Hidráulico" },
      { label: "Vida útil", value: "150,000–200,000 km" },
    ],
    symptoms: ["Pedal muy duro", "Chirrido al frenar con motor apagado", "Mayor esfuerzo al pisar el freno"],
    tips: ["Probar con motor apagado: el pedal se debe endurecer tras 2 pisadas.", "No usar el vehículo sin servofreno funcional.", "Revisar la manguera de vacío si el pedal está duro."],
  },
  "filtro-aire": {
    name: "Filtro de Aire",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Filtra el aire de admisión para proteger el motor de partículas de polvo y suciedad.",
    wear: 45, wearStatus: "warning",
    wearLabel: "45% — Cambio próximo",
    specs: [
      { label: "Tipo", value: "Papel / Espuma / Cotton" },
      { label: "Cambio recomendado", value: "Cada 15,000–30,000 km" },
    ],
    symptoms: ["Consumo elevado de combustible", "Motor sin potencia", "Humo negro del escape", "Ruido de succión inusual"],
    tips: ["Revisar visualmente en cada cambio de aceite.", "En zonas de polvo, cambiar con más frecuencia.", "No limpiar con agua — puede dañarlo."],
  },
  bujias: {
    name: "Bujías",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Generan la chispa eléctrica que enciende la mezcla de aire y combustible.",
    wear: 50, wearStatus: "warning",
    wearLabel: "50% — Revisar próximamente",
    specs: [
      { label: "Tipo", value: "Cobre / Iridio / Platino" },
      { label: "Gap", value: "0.8–1.1 mm" },
      { label: "Vida útil", value: "30,000–100,000 km" },
    ],
    symptoms: ["Dificultad al arrancar", "Motor falla o tiembla", "Consumo elevado", "Pérdida de potencia"],
    tips: ["Reemplazar en el intervalo indicado por el fabricante.", "Usar la especificación exacta del manual.", "No apretar en exceso al instalar."],
  },
  "correa-distribucion": {
    name: "Correa de Distribución",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Sincroniza el movimiento del cigüeñal y los árboles de levas del motor.",
    wear: 70, wearStatus: "critical",
    wearLabel: "70% — Atención próxima requerida",
    specs: [
      { label: "Material", value: "Caucho reforzado" },
      { label: "Cambio", value: "Cada 60,000–100,000 km" },
    ],
    symptoms: ["Ruido de golpeteo al arrancar", "Motor no arranca", "Pérdida de sincronía del motor"],
    tips: ["Cambiar en el intervalo indicado sin excepción.", "Reemplazar también la bomba de agua y tensores.", "Una correa rota puede destruir el motor."],
  },
  "bomba-combustible": {
    name: "Bomba de Combustible",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Suministra combustible desde el tanque hacia los inyectores del motor.",
    wear: 30, wearStatus: "ok",
    wearLabel: "30% — En buen estado",
    specs: [
      { label: "Tipo", value: "Eléctrica (sumergida en tanque)" },
      { label: "Presión", value: "2.5–4.5 bar" },
      { label: "Vida útil", value: "100,000–150,000 km" },
    ],
    symptoms: ["Motor no arranca", "Fallas de aceleración", "Motor se apaga en marcha", "Ruido de zumbido desde el tanque"],
    tips: ["Mantener el tanque por encima del 25% para enfriar la bomba.", "Usar combustible de calidad.", "Reemplazar el filtro con la bomba."],
  },
  "sensor-oxigeno": {
    name: "Sensor de Oxígeno",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Mide el oxígeno residual en los gases de escape para optimizar la mezcla aire/combustible.",
    wear: 35, wearStatus: "ok",
    wearLabel: "35% — En buen estado",
    specs: [
      { label: "Ubicación", value: "Antes y después del catalizador" },
      { label: "Vida útil", value: "60,000–100,000 km" },
    ],
    symptoms: ["Check engine encendido", "Consumo elevado de combustible", "Emisiones altas", "Pérdida de potencia"],
    tips: ["No ignorar el check engine — diagnosticar con escáner.", "Reemplazar en pares si hay dos sensores.", "Evitar combustible con plomo."],
  },
  "filtro-combustible": {
    name: "Filtro de Combustible",
    system: "Motor y Combustible", systemId: "motor", systemColor: "#e03030",
    desc: "Retiene partículas e impurezas del combustible antes de llegar al motor.",
    wear: 55, wearStatus: "warning",
    wearLabel: "55% — Cambio próximo recomendado",
    specs: [
      { label: "Cambio recomendado", value: "Cada 30,000–60,000 km" },
    ],
    symptoms: ["Motor falla bajo carga", "Arranque difícil", "Pérdida de potencia progresiva"],
    tips: ["Cambiar con la frecuencia indicada.", "En filtros externos, aliviar presión antes de cambiar.", "Usar filtros de calidad certificada."],
  },
  amortiguadores: {
    name: "Amortiguadores",
    system: "Suspensión", systemId: "suspension", systemColor: "#f59e0b",
    desc: "Absorben la energía cinética de los baches y vibraciones del camino.",
    wear: 55, wearStatus: "warning",
    wearLabel: "55% — Revisar próximamente",
    specs: [
      { label: "Tipo", value: "Monotubo / Bitubo" },
      { label: "Vida útil", value: "50,000–80,000 km" },
    ],
    symptoms: ["Rebote excesivo", "Vibración en el volante", "Auto baila en autopista", "Desgaste irregular de llantas"],
    tips: ["Probar presionando fuerte cada esquina: no debe rebotar más de una vez.", "Reemplazar en pares (eje completo).", "Inspeccionar sellos por fugas de aceite."],
  },
  resortes: {
    name: "Resortes",
    system: "Suspensión", systemId: "suspension", systemColor: "#f59e0b",
    desc: "Soportan el peso del vehículo y absorben impactos transmitidos por el camino.",
    wear: 25, wearStatus: "ok",
    wearLabel: "25% — En buen estado",
    specs: [
      { label: "Tipo", value: "Helicoidal / Ballesta" },
      { label: "Vida útil", value: "100,000–150,000 km" },
    ],
    symptoms: ["Vehículo más bajo de lo normal", "Inclinación a un lado", "Golpes al pasar topes"],
    tips: ["Reemplazar si hay deformación o altura desigual.", "No cortar resortes para bajar el auto.", "Instalar con protección antirruido."],
  },
  rotulas: {
    name: "Rótulas",
    system: "Suspensión", systemId: "suspension", systemColor: "#f59e0b",
    desc: "Articulación esférica que permite el movimiento entre la suspensión y el portamangueta.",
    wear: 40, wearStatus: "ok",
    wearLabel: "40% — En buen estado",
    specs: [
      { label: "Vida útil", value: "60,000–120,000 km" },
    ],
    symptoms: ["Ruido de chasquido al girar", "Juego en rueda al moverla", "Dirección imprecisa", "Desgaste irregular de llantas"],
    tips: ["Revisar el juego axial y radial regularmente.", "Engrasar en modelos con niple de engrase.", "No ignorar chasquidos — pueden ser peligrosos."],
  },
  "barra-estabilizadora": {
    name: "Barra Estabilizadora",
    system: "Suspensión", systemId: "suspension", systemColor: "#f59e0b",
    desc: "Barra metálica que conecta ambas ruedas del mismo eje para reducir el balanceo lateral.",
    wear: 20, wearStatus: "ok",
    wearLabel: "20% — En buen estado",
    specs: [
      { label: "Vida útil", value: "100,000–200,000 km (bujes cada 40,000)" },
    ],
    symptoms: ["Balanceo excesivo en curvas", "Ruido de golpeteo en baches", "Manejo impreciso"],
    tips: ["Los bujes de la barra se desgastan antes que la barra.", "Reemplazar bujes si hay ruido al pasar baches.", "Verificar los links de la barra en cada mantenimiento."],
  },
  bateria: {
    name: "Batería",
    system: "Sistema Eléctrico", systemId: "electrico", systemColor: "#3b82f6",
    desc: "Almacena energía eléctrica para el arranque y alimenta los sistemas auxiliares.",
    wear: 60, wearStatus: "warning",
    wearLabel: "60% — Vida útil media superada",
    specs: [
      { label: "Voltaje", value: "12V (convencional)" },
      { label: "Capacidad", value: "45–100 Ah según vehículo" },
      { label: "Vida útil", value: "3–5 años" },
    ],
    symptoms: ["Motor gira lento al arrancar", "Luces tenues", "Carro no arranca en frío", "Batería no retiene carga"],
    tips: ["Revisar terminales por corrosión.", "Reemplazar cada 3–4 años preventivamente.", "No dejar luces encendidas con motor apagado."],
  },
  alternador: {
    name: "Alternador",
    system: "Sistema Eléctrico", systemId: "electrico", systemColor: "#3b82f6",
    desc: "Convierte la energía mecánica del motor en electricidad para cargar la batería y alimentar el sistema.",
    wear: 30, wearStatus: "ok",
    wearLabel: "30% — En buen estado",
    specs: [
      { label: "Voltaje de carga", value: "13.8–14.4 V" },
      { label: "Vida útil", value: "100,000–150,000 km" },
    ],
    symptoms: ["Luz de batería encendida", "Batería se descarga rápido", "Luces fluctúan con el acelerador", "Ruido de rodamiento"],
    tips: ["Verificar el voltaje de carga con multímetro.", "Revisar la banda de alternador.", "Un alternador deficiente daña las baterías."],
  },
  "motor-arranque": {
    name: "Motor de Arranque",
    system: "Sistema Eléctrico", systemId: "electrico", systemColor: "#3b82f6",
    desc: "Motor eléctrico que gira el motor de combustión para iniciarlo.",
    wear: 20, wearStatus: "ok",
    wearLabel: "20% — En buen estado",
    specs: [
      { label: "Potencia", value: "0.8–2.5 kW" },
      { label: "Vida útil", value: "150,000–200,000 km" },
    ],
    symptoms: ["Clic al girar la llave", "Motor no responde", "Ruido de chirrido al arrancar", "Arranque lento"],
    tips: ["Un clic suele indicar solenoide defectuoso.", "Verificar la batería antes de culpar al arranque.", "Revisar el cableado de alta corriente."],
  },
  fusibles: {
    name: "Fusibles y Relés",
    system: "Sistema Eléctrico", systemId: "electrico", systemColor: "#3b82f6",
    desc: "Protegen los circuitos eléctricos de sobrecargas y cortocircuitos.",
    wear: 10, wearStatus: "ok",
    wearLabel: "10% — En excelente estado",
    specs: [
      { label: "Tipos", value: "ATO, Mini, Micro, Midi, Maxi" },
      { label: "Amperaje", value: "5–80A según circuito" },
    ],
    symptoms: ["Sistema eléctrico que no funciona", "Fusible fundido visible", "Componente sin energía"],
    tips: ["Llevar fusibles de repuesto en el vehículo.", "Si un fusible se funde repetidamente, hay un cortocircuito.", "No reemplazar por uno de mayor amperaje."],
  },
  radiador: {
    name: "Radiador",
    system: "Sistema de Enfriamiento", systemId: "enfriamiento", systemColor: "#06b6d4",
    desc: "Intercambiador de calor que disipa la temperatura del refrigerante al exterior.",
    wear: 35, wearStatus: "ok",
    wearLabel: "35% — En buen estado",
    specs: [
      { label: "Material", value: "Aluminio / Cobre-latón" },
      { label: "Vida útil", value: "150,000–200,000 km" },
    ],
    symptoms: ["Sobrecalentamiento", "Fugas de refrigerante", "Nivel de refrigerante bajo", "Olor dulce en el motor"],
    tips: ["Revisar el refrigerante en frío mensualmente.", "Limpiar las aletas del radiador cada año.", "No abrir el tapón en caliente."],
  },
  termostato: {
    name: "Termostato",
    system: "Sistema de Enfriamiento", systemId: "enfriamiento", systemColor: "#06b6d4",
    desc: "Válvula termostática que regula el flujo de refrigerante según la temperatura del motor.",
    wear: 45, wearStatus: "warning",
    wearLabel: "45% — Revisar en próximo mantenimiento",
    specs: [
      { label: "Temperatura de apertura", value: "82–95°C" },
      { label: "Vida útil", value: "60,000–100,000 km" },
    ],
    symptoms: ["Temperatura errática", "Motor tarda en calentar", "Sobrecalentamiento súbito", "Calefacción deficiente"],
    tips: ["Reemplazar preventivamente cada 80,000 km.", "Siempre reemplazar con el kit completo (junta incluida).", "Usar termostato OEM para mantener temperatura correcta."],
  },
  "bomba-agua": {
    name: "Bomba de Agua",
    system: "Sistema de Enfriamiento", systemId: "enfriamiento", systemColor: "#06b6d4",
    desc: "Impulsa el refrigerante a través de todo el sistema de enfriamiento.",
    wear: 40, wearStatus: "ok",
    wearLabel: "40% — En buen estado",
    specs: [
      { label: "Tipo", value: "Centrífuga" },
      { label: "Vida útil", value: "60,000–100,000 km" },
    ],
    symptoms: ["Fugas cerca de la bomba", "Ruido de rodamiento", "Sobrecalentamiento", "Refrigerante contaminado"],
    tips: ["Cambiar junto con la correa de distribución.", "Revisar el impulsor dentro de la bomba.", "Una bomba deficiente puede sobrecalentar en minutos."],
  },
  refrigerante: {
    name: "Refrigerante",
    system: "Sistema de Enfriamiento", systemId: "enfriamiento", systemColor: "#06b6d4",
    desc: "Fluido que circula por el sistema absorbiendo y disipando el calor del motor.",
    wear: 55, wearStatus: "warning",
    wearLabel: "55% — Cambio próximo recomendado",
    specs: [
      { label: "Concentración", value: "50/50 (agua + anticongelante)" },
      { label: "Cambio", value: "Cada 2 años o 40,000 km" },
    ],
    symptoms: ["Nivel bajo recurrentemente", "Color marrón u oscuro", "Motor con tendencia al sobrecalentamiento"],
    tips: ["Usar el tipo específico del fabricante (verde, rojo, azul).", "No mezclar tipos de refrigerante.", "Desechar correctamente — es tóxico para animales."],
  },
  catalizador: {
    name: "Catalizador",
    system: "Sistema de Escape", systemId: "escape", systemColor: "#f97316",
    desc: "Convierte los gases contaminantes del escape en emisiones menos dañinas para el medio ambiente.",
    wear: 40, wearStatus: "ok",
    wearLabel: "40% — En buen estado",
    specs: [
      { label: "Tipo", value: "TWC (Three-Way Catalyst)" },
      { label: "Temperatura de operación", value: "400–800°C" },
      { label: "Vida útil", value: "80,000–160,000 km" },
    ],
    symptoms: ["Olor a huevo podrido", "Pérdida de potencia", "Check engine encendido", "Fallo en prueba de emisiones"],
    tips: ["No ignorar el sensor de oxígeno — puede dañar el catalizador.", "Evitar aceite o refrigerante en la combustión.", "No golpear el fondo del vehículo."],
  },
  silenciador: {
    name: "Silenciador",
    system: "Sistema de Escape", systemId: "escape", systemColor: "#f97316",
    desc: "Reduce el ruido producido por los gases de escape al salir del motor.",
    wear: 30, wearStatus: "ok",
    wearLabel: "30% — En buen estado",
    specs: [
      { label: "Material", value: "Acero inoxidable / Al-Si" },
      { label: "Vida útil", value: "80,000–150,000 km" },
    ],
    symptoms: ["Escape muy ruidoso", "Ruido metálico bajo el auto", "Vibraciones en chasis"],
    tips: ["Revisar en levantamiento en cada mantenimiento.", "Las perforaciones son peligrosas — permiten CO2 en cabina.", "Reemplazar si hay golpes o perforaciones."],
  },
  "sensor-lambda": {
    name: "Sensor Lambda (O2)",
    system: "Sistema de Escape", systemId: "escape", systemColor: "#f97316",
    desc: "Mide el oxígeno residual en los gases de escape para ajustar la mezcla de combustible.",
    wear: 35, wearStatus: "ok",
    wearLabel: "35% — En buen estado",
    specs: [
      { label: "Señal", value: "0–1V (banda estrecha) / Variable (banda ancha)" },
      { label: "Vida útil", value: "60,000–100,000 km" },
    ],
    symptoms: ["Check engine", "Consumo de combustible elevado", "Emisiones altas", "Motor inestable en ralentí"],
    tips: ["Diagnosticar con escáner antes de reemplazar.", "Verificar el cableado antes del sensor.", "Usar llave de sensor para evitar daños."],
  },
  "tuberia-escape": {
    name: "Tubería de Escape",
    system: "Sistema de Escape", systemId: "escape", systemColor: "#f97316",
    desc: "Conduce los gases de combustión desde el motor hasta la salida trasera del vehículo.",
    wear: 25, wearStatus: "ok",
    wearLabel: "25% — En buen estado",
    specs: [
      { label: "Material", value: "Acero al carbono / Inoxidable" },
      { label: "Vida útil", value: "100,000–200,000 km" },
    ],
    symptoms: ["Ruido de escape inusual", "Olor a gases en cabina", "Vibraciones", "Corrosión visible"],
    tips: ["Inspeccionar junturas y abrazaderas.", "Los gases de escape son letales en cabina cerrada.", "El óxido avanzado requiere reemplazo de sección."],
  },
};

// ── Diagnostic Results ───────────────────────
export const diagnosticResults = [
  {
    id: "1",
    title: "Pastillas de Freno Desgastadas",
    desc: "El chirrido metálico al frenar indica que las pastillas han llegado al límite de desgaste. Requiere atención pronto.",
    priority: "Alta",
    tags: ["Frenos", "Pastillas", "Ruido"],
    system: "Sistema de Frenos",
    systemId: "frenos",
    zones: ["Ruedas delanteras"],
    when: ["Al frenar"],
    sensations: ["Fricción", "Ruido"],
  },
  {
    id: "2",
    title: "Disco de Freno con Irregularidades",
    desc: "Los discos rayados o deformados causan vibración en el pedal y ruido al frenar a bajas velocidades.",
    priority: "Media",
    tags: ["Frenos", "Disco", "Vibración"],
    system: "Sistema de Frenos",
    systemId: "frenos",
    zones: ["Ruedas delanteras"],
    when: ["Al frenar"],
    sensations: ["Vibración", "Ruido"],
  },
  {
    id: "3",
    title: "Acumulación de Polvo u Óxido",
    desc: "Después de lluvia o períodos sin uso, es normal un breve chirrido al frenar que desaparece tras pocos usos.",
    priority: "Baja",
    tags: ["Frenos", "Normal"],
    system: "Sistema de Frenos",
    systemId: "frenos",
    zones: ["Ruedas delanteras"],
    when: ["Al frenar"],
    sensations: ["Ruido"],
  },
  {
    id: "4",
    title: "Correa de Distribución Suelta",
    desc: "Un ruido de golpeteo al arrancar puede indicar desgaste o tensión insuficiente en la correa de distribución.",
    priority: "Alta",
    tags: ["Motor", "Correa", "Ruido"],
    system: "Motor y Combustible",
    systemId: "motor",
    zones: ["Motor"],
    when: ["Al arrancar"],
    sensations: ["Ruido"],
  },
  {
    id: "5",
    title: "Amortiguadores Desgastados",
    desc: "La vibración excesiva al girar o en curvas indica que los amortiguadores no absorben correctamente los impactos.",
    priority: "Media",
    tags: ["Suspensión", "Vibración"],
    system: "Suspensión",
    systemId: "suspension",
    zones: ["Suspensión"],
    when: ["Al girar", "En curvas"],
    sensations: ["Vibración"],
  },
  {
    id: "6",
    title: "Batería con Carga Baja",
    desc: "El motor gira lento al arrancar o las luces parpadean, indicando que la batería no mantiene carga suficiente.",
    priority: "Media",
    tags: ["Eléctrico", "Batería", "Arranque"],
    system: "Sistema Eléctrico",
    systemId: "electrico",
    zones: ["Eléctrico"],
    when: ["Al arrancar"],
    sensations: [],
  },
  {
    id: "7",
    title: "Catalizador Obstruido",
    desc: "Pérdida de potencia progresiva con olor a huevo puede señalar obstrucción del catalizador.",
    priority: "Media",
    tags: ["Escape", "Catalizador", "Olor"],
    system: "Sistema de Escape",
    systemId: "escape",
    zones: ["Escape"],
    when: ["En ralentí", "A alta velocidad"],
    sensations: ["Humo", "Olor"],
  },
  {
    id: "8",
    title: "Termostato Defectuoso",
    desc: "La temperatura sube y baja erráticamente porque el termostato no regula correctamente el flujo del refrigerante.",
    priority: "Alta",
    tags: ["Enfriamiento", "Termostato"],
    system: "Sistema de Enfriamiento",
    systemId: "enfriamiento",
    zones: ["Motor"],
    when: ["En ralentí", "A alta velocidad"],
    sensations: ["Calor"],
  },
];

export const filterZones = ["Ruedas delanteras", "Motor", "Transmisión", "Suspensión", "Frenos", "Eléctrico", "Escape"];
export const filterWhen = ["Al frenar", "Al arrancar", "Al girar", "En curvas", "A alta velocidad", "En ralentí"];
export const filterPriority = ["Alta", "Media", "Baja"];
export const filterSensation = ["Fricción", "Ruido", "Vibración", "Calor", "Humo", "Olor"];

export const priorityColor = { Alta: "#e03030", Media: "#f59e0b", Baja: "#10b981" };
export const priorityLabel = { Alta: "URGENCIA ALTA", Media: "URGENCIA MEDIA", Baja: "URGENCIA BAJA" };

export const notifications = [
  { id: 1, title: "Cambio de pastillas próximo", desc: "En 3 días · Toyota Corolla", type: "warning", time: "hace 2h" },
  { id: 2, title: "Diagnóstico completado", desc: "Ruido al frenar analizado", type: "success", time: "ayer" },
  { id: 3, title: "Recordatorio: Cambio de aceite", desc: "En 1 semana", type: "info", time: "hace 3 días" },
];

export const notifTypeColor = { warning: "#f59e0b", success: "#10b981", info: "#3b82f6" };

export const labelMap = {
  diagnostico: "Diagnóstico", resultado: "Resultado", perfil: "Perfil",
  sistemas: "Sistemas", frenos: "Frenos", motor: "Motor y Combustible",
  suspension: "Suspensión", electrico: "Sistema Eléctrico",
  enfriamiento: "Enfriamiento", escape: "Escape",
  "pastillas-freno": "Pastillas de Freno", "disco-freno": "Disco de Freno",
  "pinzas-freno": "Pinzas de Freno", "liquido-frenos": "Líquido de Frenos",
  "cilindro-maestro": "Cilindro Maestro", servofreno: "Servofreno",
  "filtro-aire": "Filtro de Aire", bujias: "Bujías",
  "correa-distribucion": "Correa de Distribución", "bomba-combustible": "Bomba de Combustible",
  "sensor-oxigeno": "Sensor de Oxígeno", "filtro-combustible": "Filtro de Combustible",
  amortiguadores: "Amortiguadores", resortes: "Resortes",
  rotulas: "Rótulas", "barra-estabilizadora": "Barra Estabilizadora",
  bateria: "Batería", alternador: "Alternador",
  "motor-arranque": "Motor de Arranque", fusibles: "Fusibles y Relés",
  radiador: "Radiador", termostato: "Termostato",
  "bomba-agua": "Bomba de Agua", refrigerante: "Refrigerante",
  catalizador: "Catalizador", silenciador: "Silenciador",
  "sensor-lambda": "Sensor Lambda", "tuberia-escape": "Tubería de Escape",
};
